name: Combine Zip Files

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  combine:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Navigate to the directory and combine zip files
        run: |
          cd "01.525 - BETA - very minor patch" || exit 1
          # Combine split zip files
          cat thmj4n.zip.* > thmj4n.zip

      - name: Upload Combined Zip as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: combined-zip
          path: "01.525 - BETA - very minor patch/thmj4n.zip"  # Path to the combined zip file
