name: Combine Zip Files

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  combine:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find highest version number
        id: find_version
        run: |
          # Extract version numbers from directory names
          version_dirs=$(ls -d */ | grep -oP '\d+\.\d+\.\d+')
          highest_version=$(echo "$version_dirs" | sort -V | tail -n 1)
          echo "Highest version found: $highest_version"
          echo "::set-output name=highest_version::$highest_version"

      - name: Navigate to the directory and combine zip files
        run: |
          cd "${{ steps.find_version.outputs.highest_version }}" || exit 1
          # Combine split zip files
          combined_zip_name="thmj4n ${highest_version}.zip"
          cat thmj4n.zip.* > "$combined_zip_name"

      - name: Upload Combined Zip as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: combined-zip
          path: "${{ steps.find_version.outputs.highest_version }}/thmj4n ${steps.find_version.outputs.highest_version}.zip"  # Path to the combined zip file
